# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)


# questions = Question.create(
#     [{category:0, text:"Who famously asked, 'So which one of you guys is going to come in second?' before the 1986 NBA 3-point contest.", answer_1:"Reggie Miller", answer_2:"Larry Bird", answer_3:"Magic Johnson", answer_4:"Kareem Abdul-Jabaar", correct_answer:2},
#     {category:0, text:"Which defensive standout and NBA three-point specialist earned the nickname 'Thunder'", answer_1:"Wesley Person", answer_2:"Hersey Hawkins", answer_3:"Dell Curry", answer_4:"Dan Majerle", correct_answer:4},
#     {category:0, text:"Deion sanders became one of the flashiest players in NFL history as a seven-time All Pro:", answer_1:"Linebacker", answer_2:"Cornerback", answer_3:"Running Back", answer_4:"Tight End", correct_answer:2},
#     {category:0, text:"The Foster Hewitt Memorial Award is given to hockey ____", answer_1:"Announcers", answer_2:"Goaltenders", answer_3:"Owners", answer_4:"Linesmen", correct_answer:1},
#     {category:0, text:"Which Stanley Cup winner had Phil Roberto and Leon Rochefort on its roster?", answer_1:"1961 Blackhawks", answer_2:"1981 Islanders", answer_3:"1971 Canadiens", answer_4:"1951 Maple Leafs", correct_answer:3},
#     {category:0, text:"In 1973, tennis star Chris Evert announced her engagement to:", answer_1:"Jimmy Connors", answer_2:"Frank Sinatra Jr.", answer_3:"Ilie Nastase", answer_4:"Burt Reynolds", correct_answer:1},
#     {category:0, text:"Charlie Ward took home this award after the 1993 college football season.", answer_1:"Butkus Award", answer_2:"Payton Award", answer_3:"Outland Trophy", answer_4:"Maxwell Award", correct_answer:4},
#     {category:0, text:"Which of these athletes is a member of the Hockey Hall of Fame", answer_1:"Lanny McDonald", answer_2:"Dick Weber", answer_3:"Jim Shoulders", answer_4:"Sandy Koufax", correct_answer:1},
#     {category:0, text:"His Major League resume includes 12 Gold Gloves and 4 World Series appearances.", answer_1:"Ozzie Smith", answer_2:"Duke Snider", answer_3:"Joe DiMaggio", answer_4:"Willie Mays", correct_answer:4},
#     {category:0, text:"If a golfer takes six shots on a par-3 hole, that would be called a:", answer_1:"Birdie", answer_2:"Double Eagle", answer_3:"Mashie", answer_4:"Triple Bogey", correct_answer:4},
#     {category:0, text:"Which NFL team is mismatched with its first-round draft pick in 2009?", answer_1:"Chiefs - Andre Smith", answer_2:"Seahawks - Aaron Curry", answer_3:"49ers - Michael Crabtree", answer_4:"Jets - Mark Sanchez", correct_answer:1},
#     {category:0, text:"Each of these descriptions fits NFL legend Ken Stabler except:", answer_1:"15-year Career", answer_2:"Auburn Alum", answer_3:"Drafted by Oakland", answer_4:"Played in Super Bowl XI", correct_answer:2},
#     {category:0, text:"What major college football team takes the field in uniforms of burnt orange and white?", answer_1:"Wisconsin Badgers", answer_2:"South Carolina Gamecocks", answer_3:"Temple Owls", answer_4:"Texas Longhorns", correct_answer:4},
#     {category:0, text:"The Rules Convention for college football passed a rule in 1888 that permitted:", answer_1:"Kicking Tees", answer_2:"Helmets", answer_3:"14 players per side", answer_4:"Tackling below the waist", correct_answer:4},
#     {category:0, text:"Golfing legends Nancy Lopez and Kathy Whitworth both grew up in", answer_1:"Delaware", answer_2:"Manitoba", answer_3:"Ireland", answer_4:"New Mexico", correct_answer:4},
#     {category:0, text:"He had thirteen .300 seasons and was named both regular season and World Series MVP:", answer_1:"Roberto Clemente", answer_2:"Lou Brock", answer_3:"Dave Parker", answer_4:"Johnny Bench", correct_answer:1},
#     {category:0, text:"Who was traded for six players, two number one picks and $15 million in a 1992 deal?", answer_1:"Joe Montana", answer_2:"Herschel Walker", answer_3:"Shaquille O'Neal", answer_4:"Eric Lindros", correct_answer:4},
#     {category:0, text:"Congratulations to ____ for winning the 2009 Formula One driving championship.", answer_1:"Lewis Hamilton", answer_2:"Jenson Button", answer_3:"Scott Speed", answer_4:"Kimi Raikkonen", correct_answer:2},
#     {category:0, text:"Baseball umpire Eric Gregg took a leave of absense in 1996 to enter a:", answer_1:"Buddhist Monastery", answer_2:"Marine Boot Camp", answer_3:"Reformed Gamblers Clinic", answer_4:"Weight Loss Program", correct_answer:4},
#     {category:0, text:"Which of these hoopsters won three NBA Titles in his playing career?", answer_1:"Jerry West", answer_2:"Isiah Thomas", answer_3:"Wilt Chamberlain", answer_4:"Larry Bird", correct_answer:4},
#     {category:1, text:"Physicist Robert Oppenheimer was the head of what 1950s government initiative?", answer_1:"United Nations", answer_2:"Marshall Plan", answer_3:"Manhattan Project", answer_4:"Public Words Administration", correct_answer:3},
#     {category:1, text:"Which policy did the Truman Doctrine of 1947 articulate in the Cold War fight against communism?", answer_1:"Mutually assured destruction", answer_2:"Surrender", answer_3:"Containment", answer_4:"Appeasement", correct_answer:3},
#     {category:1, text:"What were the new arrivals in California who hoped to make their fortune by mining during the Gold Rush nicknamed?", answer_1:"Cowboys", answer_2:"49ers", answer_3:"Gold Seekers", answer_4:"Dreamers", correct_answer:2},
#     {category:1, text:"Which state did Ronald Reagan govern before becoming president of the United States?", answer_1:"Arizona", answer_2:"Texas", answer_3:"California", answer_4:"New York", correct_answer:3},
#     {category:1, text:"Where was America's first drive-in movie theater located?", answer_1:"Latham, New York", answer_2:"Camden, New Jersey", answer_3:"Hollywood, California", answer_4:"Sarasota, Florida", correct_answer:2},
#     {category:1, text:"What was the first state to elect two senators to Congress?", answer_1:"Ohio", answer_2:"Pennsylvania", answer_3:"Virginia", answer_4:"New Jersey", correct_answer:2},
#     {category:1, text:"When he first appeared as a symbol of the United States in 1852, what did Uncle Sam lack?", answer_1:"Hair", answer_2:"Eyes", answer_3:"A beard", answer_4:"Suspenders", correct_answer:3},
#     {category:1, text:"In which was did the U.S. Air Force NOT take part?", answer_1:"Persian Gulf War", answer_2:"Vietnam War", answer_3:"Civil War", answer_4:"Korean War", correct_answer:3},
#     {category:1, text:"What was the main language used in ancient Rome?", answer_1:"Romanian", answer_2:"Anglo-Saxon", answer_3:"Latin", answer_4:"Italian", correct_answer:3},
#     {category:1, text:"Who was the first Roman emperor?", answer_1:"Julius", answer_2:"Tiberius", answer_3:"Nero", answer_4:"Augustus", correct_answer:4},
#     {category:1, text:"In what country did paper making originate?", answer_1:"India", answer_2:"China", answer_3:"Iran", answer_4:"Russia", correct_answer:2},
#     {category:1, text:"Which artist is considered an Abstract Expressionist sculptor?", answer_1:"David Smith", answer_2:"Gutzon Borglum", answer_3:"Auguste Rodin", answer_4:"Donatello", correct_answer:1},
#     {category:1, text:"What were the first words transmitted by Alexander Graham Bell's invention, the telephone?", answer_1:"Testing. 1. 2.", answer_2:"Ahoy!", answer_3:"Mr. Watson - Come here - I want to see you.", answer_4:"Mary Had a Little Lamb", correct_answer:3},
#     {category:1, text:"Which New Hampshire-born president spoke in support of the Confederacy during the Civil War?", answer_1:"James K. Polk", answer_2:"John Tyler", answer_3:"Franklin Pierce", answer_4:"Abraham Lincoln", correct_answer:3},
#     {category:1, text:"Which was was the longest in history?", answer_1:"Peloponnesian War", answer_2:"Vietnam War", answer_3:"Hundred Years' War", answer_4:"World War II", correct_answer:3},
#     {category:1, text:"Which Swedish diplomat saved thousands of Hungarian Jews from extermination by the Nazis during World War II?", answer_1:"Kofi Annan", answer_2:"Alfred Nobel", answer_3:"Dag Hammarskjold", answer_4:"Raoul Wallenberg", correct_answer:4},
#     {category:1, text:"The social revolution that swept Paris in 1968 originated as which type of event?", answer_1:"Draft riot", answer_2:"Student protest", answer_3:"Food riot", answer_4:"Lottery ticket riot", correct_answer:2},
#     {category:1, text:"Who became the youngest first lady when she married a U.S. president at age 21?", answer_1:"Jacqueline Kennedy", answer_2:"Hillary Clinton", answer_3:"Frances Folsom Cleveland", answer_4:"Michelle Obama", correct_answer:3},
#     {category:1, text:"What animals, brought from the West during the Lewis and Clark expedition, did Thomas Jefferson keep on the White House lawn?", answer_1:"Bears", answer_2:"Ocelots", answer_3:"Turkeys", answer_4:"Rattlesnakes", correct_answer:1},
#     {category:1, text:"From which university did Theodore Roosevelt graduate in 1880?", answer_1:"University of California", answer_2:"Brown", answer_3:"Harvard", answer_4:"Princeton", correct_answer:3},
#     {category:2, text:"Which type of geographic landforms are Iberia, Scandinavia, and Yucatan?", answer_1:"Mountains", answer_2:"Valleys", answer_3:"Islands", answer_4:"Peninsulas", correct_answer:4},
#     {category:2, text:"What is the capital of Panama?", answer_1:"Colon", answer_2:"Panama City", answer_3:"San Jose", answer_4:"San Miguelito", correct_answer:2},
#     {category:2, text:"Where is the Dolomites mountain range located?", answer_1:"Hungary", answer_2:"Czech Republic", answer_3:"Italy", answer_4:"Croatia", correct_answer:3},
#     {category:2, text:"Which of these cities is the most western?", answer_1:"Khartoum", answer_2:"Helsinki", answer_3:"Islamabad", answer_4:"Jerusalem", correct_answer:2},
#     {category:2, text:"What is the highest point in Germany?", answer_1:"Zugspitze", answer_2:"Monte Rose", answer_3:"Mont Blanc", answer_4:"Matterhorn", correct_answer:1},
#     {category:2, text:"On which continent is Austria located?", answer_1:"Africa", answer_2:"Asia", answer_3:"Australia", answer_4:"Europe", correct_answer:4},
#     {category:2, text:"What is the capitol of Japan?", answer_1:"Seoul", answer_2:"Tokyo", answer_3:"Sapporro", answer_4:"Osaka", correct_answer:2},
#     {category:2, text:"In what country can you find Cape Race?", answer_1:"Mozambique", answer_2:"Ireland", answer_3:"Canada", answer_4:"South Africa", correct_answer:3},
#     {category:2, text:"On what continent is Ethiopia located?", answer_1:"Europe", answer_2:"Africa", answer_3:"Asia", answer_4:"South America", correct_answer:2},
#     {category:2, text:"What is the longest river in Asia?", answer_1:"Yenisei", answer_2:"Yellow River", answer_3:"Ob", answer_4:"Yangtze", correct_answer:4},
#     {category:2, text:"Athens is the capital of which country?", answer_1:"North Korea", answer_2:"El Salvador", answer_3:"Greece", answer_4:"Switzerland", correct_answer:3},
#     {category:2, text:"Famous landmark can be found at 1600 Pennsylvania Avenue in which city?", answer_1:"Washington D.C.", answer_2:"Philadelphia", answer_3:"New York", answer_4:"Los Angeles", correct_answer:1},
#     {category:2, text:"Where can we find the region of Tuscany?", answer_1:"Italy", answer_2:"France", answer_3:"Austria", answer_4:"Spain", correct_answer:1},
#     {category:2, text:"Road Town is the capital of which country or territory?", answer_1:"British Virgin Island", answer_2:"Marshall Islands", answer_3:"Saint Martin", answer_4:"Jamaica", correct_answer:1},
#     {category:2, text:"The city of Melbourne lies on the banks of which river?", answer_1:"Murrumbidgee", answer_2:"Murray", answer_3:"Yarra", answer_4:"Darling", correct_answer:3},
#     {category:2, text:"Which of these cities is the most northern?", answer_1:"Dallas", answer_2:"Baghdad", answer_3:"Hong Kong", answer_4:"Athens", correct_answer:4},
#     {category:2, text:"Ojos del Salado is the highest point of which country?", answer_1:"Phillippines", answer_2:"Cuba", answer_3:"Chile", answer_4:"Spain", correct_answer:3},
#     {category:2, text:"Which of these is the largest river by discharge of water in the world?", answer_1:"Mekong", answer_2:"Mississippi", answer_3:"Nile", answer_4:"Amazon", correct_answer:4},
#     {category:2, text:"The city of Perth is on which body of water?", answer_1:"Indian Ocean", answer_2:"Pacific Ocean", answer_3:"Timor Sea", answer_4:"Tasman Sea", correct_answer:1},
#     {category:2, text:"Where is South Georgia Island?", answer_1:"Persian Gulf", answer_2:"Pacific Ocean", answer_3:"Caribbean Sea", answer_4:"Atlantic Ocean", correct_answer:4},
#     {category:3, text:"Who has won the most Academy Awards for Best Actress?", answer_1:"Helen Mirren", answer_2:"Judi Dench", answer_3:"Meryl Streep", answer_4:"Katherine Hepburn", correct_answer:4},
#     {category:3, text:"The film 'La Vie en Rose' ('La Môme') in 2007 followed the life of which French artist?", answer_1:"Film director Yves Montand", answer_2:"Painter Edouard Manet", answer_3:"Fashion designer Coco Chanel", answer_4:"Singer Edith Piaf", correct_answer:4},
#     {category:3, text:"Shirley Conran's book 'Superwoman', published in 1975, was about what?", answer_1:"Household management", answer_2:"Career advice", answer_3:"Graphic novel about a super-heroine", answer_4:"Teenage promiscuity", correct_answer:1},
#     {category:3, text:"Which of these is a book that was the subject of a British obscenity trial in 1960?", answer_1:"Lady Chatterley's Lover", answer_2:"Deep Throat", answer_3:"Last Tango In Paris", answer_4:"A Clockwork Orange", correct_answer:1},
#     {category:3, text:"Which of these characters appeared in 'My Fair Lady'?", answer_1:"Professor Challenger", answer_2:"Professor Higgins", answer_3:"Professor Plum", answer_4:"Professor Moriarty", correct_answer:2},
#     {category:3, text:"The US television serials 'The Good Wife', 'Canterbury's Law' and 'ER' all have or have had which actor as one of the leads?", answer_1:"Archie Panjabi", answer_2:"Aidan Quinn", answer_3:"Julianna Margulies", answer_4:"Makenzie Vega", correct_answer:3},
#     {category:3, text:"The US television serials 'The Good Wife', 'Canterbury's Law' and 'ER' all have or have had which actor as one of the leads?", answer_1:"Archie Panjabi", answer_2:"Aidan Quinn", answer_3:"Julianna Margulies", answer_4:"Makenzie Vega", correct_answer:3},
#     {category:3, text:"What is the setting for the John Carpenter film 'Halloween'?", answer_1:"Amity Island", answer_2:"Bodega Bay", answer_3:"Haddonfield, Illinois", answer_4:"Black Lake, Maine", correct_answer:3},
#     {category:3, text:"Banksy's 2015 work on the walls of a ruined building in the Gaza Strip, Palestine, depicts what?", answer_1:"A kitten with a bow", answer_2:"A dog urinating on a gun", answer_3:"An unknown old man", answer_4:"A parachuting rat", correct_answer:1},
#     {category:3, text:"Who said it 'Don't Matter' in 2007?", answer_1:"Akon", answer_2:"Usher", answer_3:"Jay-Z", answer_4:"Ne-Yo", correct_answer:1},
#     {category:3, text:"'The Hunchback of Notre Dame' was originally written in what language?", answer_1:"German", answer_2:"French", answer_3:"Spanish", answer_4:"Russian", correct_answer:2},
#     {category:3, text:"In 'The Sound of Music', which of these items did not feature in Maria's list of 'Favourite Things'?", answer_1:"Apple strudel", answer_2:"Polished shoes", answer_3:"Schnitzel with noodles", answer_4:"Geese", correct_answer:2},
#     {category:3, text:"Which US TV show, where the star appeared as a fictionalised version of himself with his friends George Costanza, Elaine Benes and Cosmo Kramer, ran for 9 seasons?", answer_1:"Letterman", answer_2:"Frasier", answer_3:"The Fresh Prince of Bel Air", answer_4:"Seinfeld", correct_answer:4},
#     {category:3, text:"Which was the first of these Disney films to be released?", answer_1:"The Jungle Book", answer_2:"The Lion King", answer_3:"The Aristocats", answer_4:"The Little Mermaid", correct_answer:1},
#     {category:3, text:"Complete the title of this James Bond film: 'You Only Live ... '", answer_1:"Twice", answer_2:"Once", answer_3:"It Down", answer_4:"Slowly", correct_answer:1},
#     {category:3, text:"What fully-fledged fictional language, which has a number of typologically uncommon features, was deliberately designed to be 'non-human' by Marc Okrand?", answer_1:"Klingon", answer_2:"Lapine", answer_3:"Qenya", answer_4:"Newspeak", correct_answer:1},
#     {category:3, text:"Which is the painting known by Italians as 'La Gioconda'?", answer_1:"Whistler's Mother", answer_2:"The Laughing Cavalier", answer_3:"Girl with a Pearl Earring", answer_4:"Mona Lisa", correct_answer:4},
#     {category:3, text:"The podcast which grew out of 'This American Life', and first aired in 2014, is called...?", answer_1:"Housewives", answer_2:"Serial", answer_3:"Criminal", answer_4:"Where", correct_answer:2},
#     {category:3, text:"The US TV series 'Mad Men' centres around what industry or profession?", answer_1:"Cheese making", answer_2:"Psychological therapy", answer_3:"Advertising", answer_4:"Selling toys", correct_answer:3},
#     {category:3, text:"How many books are there in the 'Harry Potter' series by J K Rowling?", answer_1:"10", answer_2:"5", answer_3:"7", answer_4:"8", correct_answer:3},
#     {category:4, text:"What sort of creature is a lurcher?", answer_1:"Bird", answer_2:"Butterfly", answer_3:"Dog", answer_4:"Rabbit", correct_answer:3},
#     {category:4, text:"Making a U-turn results in a change of direction of how many degrees?", answer_1:"180", answer_2:"360", answer_3:"90", answer_4:"270", correct_answer:1},
#     {category:4, text:"What is the name for a nutritional disease caused by a lack of vitamin c?", answer_1:"Scabies", answer_2:"Scurvy", answer_3:"Piles", answer_4:"Shingles", correct_answer:2},
#     {category:4, text:"What is the force that causes unsupported objects to fall to the ground?", answer_1:"Cavity", answer_2:"Sagacity", answer_3:"Strategy", answer_4:"Gravity", correct_answer:4},
#     {category:4, text:"What is an geminid?", answer_1:"Someone born under the star sign Gemini", answer_2:"A type of meteorite", answer_3:"A twin", answer_4:"A quasi gemstone", correct_answer:2},
#     {category:4, text:"Digitalis is a genus of about 20 species of herbaceous perennials, shrubs, and biennials that are commonly called … ?", answer_1:"Hyacinth", answer_2:"Deadly nightshade", answer_3:"Hemlock", answer_4:"Foxglove", correct_answer:4},
#     {category:4, text:"Teal, mallard, muscovy and mandarin are all types of what?", answer_1:"Cow", answer_2:"Cheese", answer_3:"Duck", answer_4:"Reptile", correct_answer:3},
#     {category:4, text:"What is produced by the cortex of supra-renal glands that stimulates the autonomic nervous system?", answer_1:"Glycerine", answer_2:"Mescalin", answer_3:"Niacin", answer_4:"Adrenalin", correct_answer:4},
#     {category:4, text:"Which of these is not a member of the group of vitamins called Vitamin B?", answer_1:"Tetrahydrocannabinol", answer_2:"Thiamine", answer_3:"Riboflavin", answer_4:"Niacin", correct_answer:1},
#     {category:4, text:"What was the name for a foul smell believed to carry diseases, since discredited by the discovery of infectious agents?", answer_1:"Seepage", answer_2:"Majorca", answer_3:"Moa Point", answer_4:"Miasma", correct_answer:4},
#     {category:4, text:"Over 99.9% of an atom's mass is concentrated in what part of the atom?", answer_1:"Nucleus", answer_2:"Periphery", answer_3:"Cranium", answer_4:"Orbitals", correct_answer:1},
#     {category:4, text:"Trypanosomiasis is an infectious disease spread by what?", answer_1:"Mice", answer_2:"Fleas", answer_3:"Tsetse fly", answer_4:"Armadillos", correct_answer:3},
#     {category:4, text:"What is petrology the study of?", answer_1:"Oil", answer_2:"Rolls", answer_3:"Rocks", answer_4:"Plants", correct_answer:1},
#     {category:4, text:"Which of these is a citrus fruit?", answer_1:"Geraldine", answer_2:"Clementine", answer_3:"Christine", answer_4:"Emmeline", correct_answer:2},
#     {category:4, text:"What is the longest and widest single nerve in the human body?", answer_1:"Sciatic nerve", answer_2:"Lateral femoral cutaneous nerve", answer_3:"Optic nerve", answer_4:"Saphenous nerve", correct_answer:1},
#     {category:4, text:"All snowflakes are geometric figures with how many sides?", answer_1:"12", answer_2:"4", answer_3:"6", answer_4:"5", correct_answer:3},
#     {category:4, text:"When was observational evidence first accepted by the scientists of the time that the Milky Way is not the only galaxy in the universe?", answer_1:"1927", answer_2:"1929", answer_3:"1925", answer_4:"1895", correct_answer:2},
#     {category:4, text:"In astrophysics and physical cosmology, what is Olbers's paradox, named after the German astronomer Heinrich Wilhelm Olbers (1758–1840).", answer_1:"The dark night sky paradox", answer_2:"The faint young Sun paradox", answer_3:"The paradoxical reaction of a comet's tail as it passes a star", answer_4:"The heat death paradox", correct_answer:1},
#     {category:4, text:"What, if decreased, will lower the boiling point of water?", answer_1:"Altitude", answer_2:"Pressure", answer_3:"Salt content", answer_4:"Temperature", correct_answer:2},
#     {category:4, text:"What is the more common name for the white crystalline salt called hydrated sodium pyroborate?", answer_1:"Fire lighters", answer_2:"Heroin", answer_3:"Borax", answer_4:"Boron", correct_answer:3}])

# game = Game.create([{room_id:"",p1:"",p1_bet:0.01,p2:"",p2_bet:0.01}])